---
- name: "reload : reload Jenkins configuration as code configuration."
  jenkins_script:
    script: "{{ lookup('file', 'files/groovy/jcasc/reload.groovy') }}"
    user: "{{ jenkins_casc_admin_username }}"
    password: "{{ jenkins_casc_admin_password }}"
    url: "{{ jenkins_casc_jenkins_base_url }}"
    timeout: "{{ jenkins_casc_script_timeout }}"
    args:
      jcasc_path: "{{ jenkins_casc_config_path }}"
  register: _jenkins_casc_upload_files_result
  tags:
    - jcasc-reload

- name: "reload : set _jenkins_casc_upload_files_result fact."
  ansible.builtin.set_fact:
    _jenkins_casc_upload_files_result:
      "{{ (_jenkins_casc_upload_files_result.output | regex_replace('\\s*Result:\\s*(.*)\\n*$', '\\1') | from_json) }}"

- name: "reload : fail when configuration throws exception."
  ansible.builtin.fail:
    msg:
      - Exception thrown during applying of configuration, check your configuration!
      - "{{ _jenkins_casc_upload_files_result.msg }}"
  when: _jenkins_casc_upload_files_result.failed
